name: Gerar Executavel Windows

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Permite apertar um botão para fabricar manualmente

jobs:
  build:
    runs-on: windows-latest # Usa um servidor Windows da Microsoft

    steps:
    - name: Baixar o codigo do repositorio
      uses: actions/checkout@v4

    - name: Configurar o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 

    - name: Instalar bibliotecas matematicas e o PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl python-bcb pyinstaller
        
    - name: Fabricar o arquivo .exe (Dr. Nash)
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon=dr_nash.ico --name="Nash_System" nash.py

    - name: Salvar o .exe para download
      uses: actions/upload-artifact@v4
      with:
        name: Nash_System_Windows
        path: dist/Nash_System.exe
