name: Gerar Instalador Windows

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Baixar o codigo do repositorio
      uses: actions/checkout@v4

    - name: Configurar o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar bibliotecas fixadas
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Fabricar o aplicativo Windows (OneFile)
      run: |
        pyinstaller --noconfirm --windowed --onefile --icon=dr_nash.ico --add-data "dr_nash.ico;." nash.py

    - name: Compilar o Instalador (Inno Setup)
      run: iscc gerador_nash.iss

    - name: Salvar Instalador para download
      uses: actions/upload-artifact@v4
      with:
        name: Instalador_Nash_System
        path: Instalador_Final/Instalador_Nash_System.exe